[default]
FileStorePath=/Users/flokilab/projects/java/fixdata/acceptor/acceptor_store
FileLogPath=/Users/flokilab/projects/java/fixdata/acceptor/acceptor_log
ConnectionType=acceptor
StartTime=00:00:00
EndTime=00:00:00
HeartBtInt=30
ResetOnLogon=Y
ResetOnLogout=Y
ResetOnDisconnect=Y
SocketAcceptPort=9876
UseDataDictionary=N
BeginString=FIX.4.4
SendRedundantResendRequests=N

[session]
SenderCompID=acceptor
TargetCompID=initiator